"""empty message

Revision ID: bfbfff99bac9
Revises: 16b86ff7fcbc
Create Date: 2022-09-03 08:49:24.635508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfbfff99bac9'
down_revision = '16b86ff7fcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'userId')
    op.drop_column('product', 'createdAt')
    # ### end Alembic commands ###
